---
title: 'Lab 9: Final Project Organization'
author: "STAT 345"
output: word_document
---

We will communicate via our group chat on messages.
We'll communicate at least once a week, and more as we begin to work more on the project, to tell everyone what we've worked on and establish expectations for what we will do over the next week.

Parts we are intending to work on:
- Find and summarize monopoly rules (Part 1)
-	Simulate a dice roll
- Determine which properties are landed on most
- Create a visualization for frequency of landing on each property


https://github.com/kbaasch/STAT345---Final 

4. Discuss with your project team the aspects of the project described in the provided project file. How and when will you communicate? Which parts are you intending to work on? 
5. Submit a short Word document that includes your initial decisions regarding task assignments. Include a link to the team project repository (GitHub) in this document. (Task assignments can change -- you won't be locked into today's decisions regarding tasks)
