---
title: "STAT 345 Final Project - Real Estate"
author: "STAT 345"
output: html_document
---

Expected Submission: You will generate a well-written R Markdown report that addresses the following prompts. This R Markdown report should source your analysis code and only display top-level, abstracted code _if/when appropriate_. Choices made during the analysis project should be described and justified in the report. 


Advice for getting started:

- Start a conversation chain with your group members. Email is a great place to start, but other options exist (texting, social media platforms, etc.). Set some reasonable expectations for how and when you plan to respond to conversations. It is likely going to be unacceptable to only respond once per week, for example, but also likely unacceptable to expect a response within the hour. Have an honest conversation with your group members about this issue.
- Start the project from a "top-down design" perspective. So, determine what the major steps of the process are, and determine what the inputs and outputs are for each of those steps (the output of step 1 will likely be the input for step 2, for example). This step is much like writing an outline for a paper before you start to write the paper itself, only much more valuable in a group setting. 
- Once you have a sense of the big picture (the outline), determine some "due dates" for each step of the process. Work backwards from the final submission date, giving yourselves time to work on each of the parts as needed. Given the top-down design, you should be able to "divide and conquer" -- working on parts of the project that depend on earlier steps.
- Decide how you plan to share code with each other. Using Git and GitHub is a really good choice here. If not, perhaps some form of shared directory online. In a worst-case scenario, email could also work. 
- Be prepared to give Dr. Baumann (at least) weekly updates on your progress. Some of this can be done via email, but discuss with your group about times you are each available to meet online as well (in an office-hour-like setting). Feel free to request meetings with Dr. Baumann to get help.

**General advice:** Get started early. If you wait to the last minute, it will not go well. For this project, you may find yourself spending a reasonable amount of time _searching_ for help.

1. _Rules!_ Monopoly has several rules related to movement around the game board. Movement is affected by standard dice rolls, special conditions for some dice rolls, and game cards. Find and summarize these rules. 

2. _Let's Get Moving_ Build a system that allows for up to 4 players to move around the game board. As a first attempt, focus on standard dice rolls, ignoring additional rules related to rolling doubles, jail, or special cards. Which properties are landed on most frequently? Create a visualization for this!

3. _Double Down_ Improve your system to incorporate going to jail, including the doubles-rolling condition. Which properties are landed on most frequently now? Has this changed dramatically from the previous system (that didn't account for jail)? Again, visualize this!

4. _Take a Chance_ Incorporate the movement cards into your system. You can ignore the effects of non-movement cards, but not their existence! Which properties are landed on most frequently now? Has this changed dramatically from the previous system (that didn't account for Chance)? Again, visualize this!

5. _Play a Game_ Extend your system to allow for up to 4 players to "play" the game. You may choose a reasonable starting board and player money level (so, you don't have to buy properties). Include payments between players, payments to the bank, and payments from the bank (there are several cards that will effect these that you should account for). You do not need to consider mortgaging properties (so a player loses when their liquid cash has run out). How long do games typically last given your starting board and money level? How does this change if money paid to the bank is placed in "Free Parking" and awarded to players landing on that space?




##WORK IN PROGRESS

double_down = function(location) {
  dice_roll_1 <- sample(1:2, 1, replace = TRUE)
  dice_roll_2 <- sample(1:2, 1, replace = TRUE)
  
  roll_total <- sum(dice_roll_1, dice_roll_2)
  roll_double <- dice_roll_1 == dice_roll_2
  
  print("roll was")
  print(roll_total)
    
  if (roll_double) {
    
    dice_roll_3 <- sample(1:2, 1, replace = TRUE)
    dice_roll_4 <- sample(1:2, 1, replace = TRUE)
    
    roll_total_2 <- sum(dice_roll_3, dice_roll_4)
    roll_double_2 <- dice_roll_3 == dice_roll_4
    
    print("roll double was")
    print(roll_total_2)

    
    if (roll_double_2) {
      dice_roll_5 <- sample(1:2, 1, replace = TRUE)
      dice_roll_6 <- sample(1:2, 1, replace = TRUE)
      
      roll_total_3 <- sum(dice_roll_5, dice_roll_6)
      roll_double_3 <- dice_roll_5 == dice_roll_6
      
      print("roll double was")
      print(roll_total_3)
      
      if (roll_double_3) {
        location = 11 #Jail
        print("doubles, doubles, doubles")
        print("You're going to JAIL!")
        
      } else {
        location = location + roll_total + roll_total_2 + roll_total_3
        print("doubles, doubles, not doubles")
        print("You're moving forward...")
        print(roll_total + roll_total_2 + roll_total_3)
      }
    } else {
      location = location + roll_total + roll_total_2
      print("doubles, not doubles")
      print("You're moving forward...")
      print(roll_total+roll_total_2)
    }
  } else {
    location = location + roll_total
    print("no doubles")
    print("You're moving forward...")
    print(roll_total)
  }

    
  if (location <= 40) {
    location = location
  } else {
    location = location - 40
  }

  
  print("You're on space...")
  print(location)
}

double_down(1)
